disabled_rules: # rule identifiers to exclude from running

opt_in_rules: # some rules are only opt-in
  - attributes
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - empty_count
  - explicit_init
  # Use type inference
  # - explicit_type_interface
  # Disabled, because Extensions in external Frameworks needs public access
  # - extension_access_modifier 
  - fatal_error_message
  - force_unwrapping
  # - explicit_top_level_acl
  # - file_header
  - first_where
  - implicit_return
  - implicitly_unwrapped_optional
  - let_var_whitespace
  - multiline_parameters
  - nimble_operator
  # - no_extension_access_modifier
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  # - sorted_imports
  - strict_fileprivate
  - switch_case_on_newline
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
  - iOSProject
  - iOSProjectTests
  - Core/Core
  - Core/CoreTests


excluded:
  - Carthage

identifier_name:
  min_length: 2
  max_length:
    warning: 40
    error: 50

line_length: 140

type_body_length:
  warning: 200
  error: 400

file_length:
  warning: 500
  error: 750

type_name:
  min_length: 4
  max_length:
    warning: 40
    error: 50

implicitly_unwrapped_optional:
  severity: error

reporter: "xcode"
